//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ListExplorer.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_LISTEXTYPE                  129
#define IDB_BALLS                       130
#define IDB_SM_BALLS                    131
#define IDR_CONTEXTMENU                 133
#define IDD_Name                        134
#define IDD_PROPERTIES                  135
#define IDC_name                        1000
#define IDC_archive                     1002
#define IDC_compressed                  1003
#define IDC_directory                   1004
#define IDC_readonly                    1005
#define IDC_system                      1006
#define IDC_sparse                      1007
#define IDC_hidden                      1008
#define IDC_hormal                      1009
#define IDC_encrypted                   1010
#define ID_Icon                         32771
#define ID_List                         32772
#define ID_Report                       32773
#define ID_Small                        32774
#define ID_PATH                         32775
#define ID_FILE_COPY                    32776
#define ID_FILE_MOVE                    32777
#define ID_FILE_DELETE                  32778
#define ID_FILE_COPY_AS                 32779
#define ID_FILE_MOVE_AS                 32780
#define ID_FILE_CUT                     32781
#define ID_FILE_PASTE                   32782
#define ID_FILE_COPYC                   32783
#define ID_FILE_CREATE                  32787
#define ID_CREATE_DIRECTOR              32788
#define ID_PROPERTY                     32789
#define ID_RENAME                       32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
